-- Sequence Ω.10: Adaptive Guardian Recalibration Engine

-- 1. Create guardian_recalibration_log table
CREATE TABLE IF NOT EXISTS guardian_recalibration_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recalibrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    previous_trust_index FLOAT NOT NULL,
    new_trust_index FLOAT NOT NULL,
    calibration_error FLOAT NOT NULL,
    playbooks_adjusted BOOLEAN DEFAULT FALSE,
    adjustments JSONB DEFAULT '{}'::JSONB,
    trigger_reason TEXT,
    notes TEXT,
    CONSTRAINT check_trust_index_range CHECK (new_trust_index >= 0 AND new_trust_index <= 1),
    CONSTRAINT check_window_valid CHECK (window_start < window_end)
);

CREATE INDEX IF NOT EXISTS idx_guardian_recalibration_log_recalibrated_at ON guardian_recalibration_log(recalibrated_at);

-- 2. Create intervention_outcomes table
CREATE TABLE IF NOT EXISTS intervention_outcomes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guardian_action_id UUID NOT NULL REFERENCES guardian_action_events(id),
    future_chain_id UUID NOT NULL REFERENCES future_chain(id),
    predicted_state TEXT,
    actual_state TEXT,
    intervention_prevented_collapse BOOLEAN DEFAULT FALSE,
    effectiveness_score FLOAT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT check_effectiveness_score_range CHECK (effectiveness_score >= 0 AND effectiveness_score <= 1)
);

CREATE INDEX IF NOT EXISTS idx_intervention_outcomes_guardian_action_id ON intervention_outcomes(guardian_action_id);
CREATE INDEX IF NOT EXISTS idx_intervention_outcomes_future_chain_id ON intervention_outcomes(future_chain_id);

-- 3. Create fn_trigger_guardian_recalibration function
CREATE OR REPLACE FUNCTION fn_trigger_guardian_recalibration(p_window_hours INT DEFAULT 24)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    v_window_end TIMESTAMPTZ := now();
    v_window_start TIMESTAMPTZ := v_window_end - (p_window_hours || ' hours')::INTERVAL;
    v_prev_trust_index FLOAT;
    v_new_trust_index FLOAT;
    v_calibration_error FLOAT;
    v_log_id UUID;
BEGIN
    -- Get latest trust index (default to 0.5 if not found)
    SELECT guardian_trust_index INTO v_prev_trust_index
    FROM continuation_metrics
    ORDER BY computed_at DESC
    LIMIT 1;

    IF v_prev_trust_index IS NULL THEN
        v_prev_trust_index := 0.5;
    END IF;

    -- Compute new trust index from future_chain_realizations in the window
    -- We'll use AVG(accuracy_score) as the proxy for trust index
    SELECT AVG(accuracy_score) INTO v_new_trust_index
    FROM future_chain_realizations
    WHERE created_at >= v_window_start AND created_at <= v_window_end;

    -- If no realizations, keep the previous index
    IF v_new_trust_index IS NULL THEN
        v_new_trust_index := v_prev_trust_index;
    END IF;

    -- Compute calibration error
    v_calibration_error := ABS(v_new_trust_index - v_prev_trust_index);

    -- Insert log
    INSERT INTO guardian_recalibration_log (
        window_start,
        window_end,
        previous_trust_index,
        new_trust_index,
        calibration_error,
        playbooks_adjusted,
        adjustments,
        trigger_reason,
        notes
    ) VALUES (
        v_window_start,
        v_window_end,
        v_prev_trust_index,
        v_new_trust_index,
        v_calibration_error,
        FALSE,
        '{}'::JSONB,
        'scheduled',
        'Auto-generated by fn_trigger_guardian_recalibration'
    ) RETURNING id INTO v_log_id;

    RETURN v_log_id;
END;
$$;

-- 4. Create view_guardian_effectiveness
CREATE OR REPLACE VIEW view_guardian_effectiveness AS
SELECT
    ga.id AS action_id,
    ga.chosen_action,
    ga.severity,
    ga.lattice_state AS predicted_state,
    io.actual_state,
    io.intervention_prevented_collapse,
    io.effectiveness_score,
    ga.collapse_probability AS projected_probability,
    NULL::FLOAT AS guardian_influence, -- Placeholder as column does not exist
    ga.created_at AS action_taken_at,
    io.created_at AS outcome_recorded_at
FROM
    guardian_action_events ga
JOIN
    intervention_outcomes io ON io.guardian_action_id = ga.id
JOIN
    future_chain fc ON io.future_chain_id = fc.id;
