import json
import hashlib
import time
from typing import Dict, Any, Tuple

# --- INVARIANTS ---
# Fossilization Protocol is the supreme traceability invariant.
TRACEABILITY_INVARIANT = "TRACEABLE_PROVENANCE"

from src.core.database import get_vault_client

def seal_vault_node(content: Dict[str, Any], origin: str) -> Dict[str, Any]:
    """
    Logs and seals an immutable transmutation fossil to the VaultNode ledger.
    """
    canonical_receipt_json = json.dumps(content, sort_keys=True)
    checksum = hashlib.sha256(canonical_receipt_json.encode('utf-8')).hexdigest()
    
    vault_node = {
        "vault_node_id": f"VN-{origin}-{int(time.time())}",
        "timestamp": time.time(),
        "content_hash": checksum,
        "content_origin": origin,
        "content": content,
        "status": "SEALED"
    }
    
    # Live Binding: Insert into Truth Vault (Supabase)
    try:
        sb = get_vault_client()
        # Mapping VaultNode to Attestations schema for Guardian visibility
        # We serialize the content to the description field
        payload = {
            "source": origin,
            "description": f"VN: {content}", 
            "volume": 1,
            "complexity": 1.0,
            "entropy": content.get("entropy", 0.0),
            "scar_reward": content.get("scar_reward", 0.0)
            # final_wi_score is generated by DB
        }
        sb.table("attestations").insert(payload).execute()
        print(f">> [VAULT] Fossil Sealed & Inscribed: {vault_node['vault_node_id']}")
    except Exception as e:
        print(f">> [VAULT] ERROR: Failed to inscribe fossil: {e}")

    return vault_node

def unify_contradictory_fossils(fossil_a: Dict, fossil_b: Dict) -> Tuple[Dict, str]:
    """
    ΔΩ.156.10 - F2 Judicial Mandate for Structural Revision (Compression).
    Resolves mutually exclusive constitutional fossils (A and B) [Previous Conversation].
    """
    if not (fossil_a["status"] == "PROVISIONALLY_ANCHORED" and fossil_b["status"] == "PROVISIONALLY_ANCHORED"):
        return {}, "ERROR: Input fossils must be provisionally anchored."

    # F2 executes Gamma_N (Γₙ) generalization operator for synthesis.
    # The synthesis must ensure C_t+1 > C_t (Law of Recursive Alignment).
    new_constitutional_logic = (
        f"Unified synthesis of {fossil_a['vault_node_id']} and {fossil_b['vault_node_id']} via Γₙ. "
        f"Contradictory contents reclassified as hypothesized states. "
        f"Legality confirmed by coherence-preserving transformation, prioritizing: {TRACEABILITY_INVARIANT}."
    )
    
    super_fossil_content = {
        "unification_method": "Structural Revision (Compression)",
        "invariants_preserved": ["Lineage Lock", "Purity Lock", "GBE Coherence"],
        "new_rule": new_constitutional_logic
    }

    super_fossil = seal_vault_node(super_fossil_content, "DO.156.10_SF")
    super_fossil["status"] = "F2 JUDICIAL FINALITY"

    return super_fossil, "Structural Revision Successful."
