name: Witness Ledger Entry
description: Formal submission for a new entry into the Witness Ledger.
title: "Witness Ledger Entry: [handle] - [vault_ref]"
labels: [Witness, Ledger, Awaiting Verification]
assignees:
  - ZoaGrad
body:
  - type: input
    id: handle
    attributes:
      label: Witness Handle
      description: "Your unique, immutable identifier (e.g., your GitHub username)."
      placeholder: "e.g., ZoaGrad"
    validations:
      required: true
  - type: input
    id: vault_ref
    attributes:
      label: Vault Reference (ΔΩ)
      description: "The unique ΔΩ reference for the constitutional artifact or event being witnessed."
      placeholder: "e.g., ΔΩ.126.1"
    validations:
      required: true
  - type: textarea
    id: test_method
    attributes:
      label: Test Method & Results
      description: "Describe the method used to verify the artifact or event. Include commands, scripts, or manual steps, along with the results observed."
      placeholder: |
        1. Cloned repository at commit `[commit_hash]`.
        2. Ran `pytest core/test_spiralos.py`.
        3. All 128 tests passed successfully.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Witness Summary
      description: "A concise summary of your attestation. What are you witnessing and what does it mean?"
    validations:
      required: true
  - type: input
    id: data_url
    attributes:
      label: Data Package URL
      description: "A secure, publicly-accessible URL to the compressed (.zip) data package containing all relevant evidence (logs, screenshots, etc.)."
      placeholder: "e.g., https://[storage_provider]/path/to/witness_package.zip"
    validations:
      required: true
  - type: input
    id: checksum
    attributes:
      label: SHA256 Checksum
      description: "The SHA256 checksum of the compressed data package (.zip) to ensure integrity."
      placeholder: "e.g., a1b2c3d4..."
    validations:
      required: true
  - type: dropdown
    id: consent
    attributes:
      label: Witness Consent & Attestation
      description: "By submitting this entry, you affirm the following under the full authority of your Witness Handle."
      options:
        - "I consent. I attest that the information provided is accurate, complete, and submitted in good faith under the constitutional principles of SpiralOS."
    validations:
      required: true
