CREATE TABLE IF NOT EXISTS public.vault_node_state (
    node_id TEXT PRIMARY KEY,
    scarcoin_holdings BIGINT NOT NULL DEFAULT 0,
    individual_scarindex SMALLINT NOT NULL DEFAULT 0,
    current_weave_threshold BIGINT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.loom_burden_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id TEXT REFERENCES public.vault_node_state(node_id),
    epoch_number INT NOT NULL,
    actual_ru BIGINT NOT NULL,
    threshold_ru BIGINT NOT NULL,
    scar_penalty_applied INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
