-- Migration: evolve_governance_schema
-- Description: Adds generic proposal fields to the existing governance_proposals table.

ALTER TABLE governance_proposals
ADD COLUMN IF NOT EXISTS title TEXT DEFAULT 'System Proposal',
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT 'Generated by System Reflection',
ADD COLUMN IF NOT EXISTS proposer_id TEXT DEFAULT 'system',
ADD COLUMN IF NOT EXISTS proposal_type TEXT DEFAULT 'constitutional_amendment',
ADD COLUMN IF NOT EXISTS payload JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS execution_result JSONB;

-- Update existing rows to have meaningful defaults if they are null
UPDATE governance_proposals 
SET title = 'System Proposal ' || substring(id::text, 1, 8),
    description = 'Automated proposal based on system reflection.',
    proposer_id = 'system',
    proposal_type = 'constitutional_amendment'
WHERE title IS NULL OR title = 'System Proposal';

-- Ensure governance_votes exists and has correct columns
CREATE TABLE IF NOT EXISTS governance_votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id UUID REFERENCES governance_proposals(id),
    voter_id TEXT NOT NULL,
    vote_choice TEXT NOT NULL, -- 'yes', 'no', 'abstain'
    vote_power NUMERIC DEFAULT 1.0,
    reason TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_votes_proposal ON governance_votes(proposal_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_votes_unique ON governance_votes(proposal_id, voter_id);

-- RLS for votes (if not already set)
ALTER TABLE governance_votes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'governance_votes' AND policyname = 'Service role full access votes'
    ) THEN
        CREATE POLICY "Service role full access votes" ON governance_votes FOR ALL USING (auth.role() = 'service_role');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'governance_votes' AND policyname = 'Public read votes'
    ) THEN
        CREATE POLICY "Public read votes" ON governance_votes FOR SELECT TO anon USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'governance_votes' AND policyname = 'Auth insert votes'
    ) THEN
        CREATE POLICY "Auth insert votes" ON governance_votes FOR INSERT TO authenticated WITH CHECK (true);
    END IF;
END $$;
